const types = {
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    SIGNUP_FAILED: 'SIGNUP_FAILED',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    PASSWORD_LINK_SENT: 'PASSWORD_LINK_SENT',
    PASSWORD_RESET: 'PASSWORD_RESET',
    FIRST_LOGIN: 'FIRST_LOGIN',

};

export default types;
