const types = {
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    SIGNUP_FAILED: 'SIGNUP_FAILED',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    PASSWORD_LINK_SENT: 'PASSWORD_LINK_SENT',
    PASSWORD_RESET: 'PASSWORD_RESET',
    FIRST_LOGIN: 'FIRST_LOGIN',
    SHOW_SIGNUP_MODAL: 'SHOW_SIGNUP_MODAL',
    CLOSE_SIGNUP_MODAL: 'CLOSE_SIGNUP_MODAL',
    CLOSE_SIGNIN_MODAL: 'CLOSE_SIGNIN_MODAL',
    SHOW_SIGNIN_MODAL: 'SHOW_SIGNIN_MODAL',
};

export default types;
